# Generated by Django 6.0.2 on 2026-03-03 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_jobseekeraccount_is_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rank', models.IntegerField(unique=True)),
                ('is_higher_education', models.BooleanField(default=False)),
                ('is_foreign', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Education Level',
                'verbose_name_plural': 'Education Levels',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='EthnicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Ethnic Group',
                'verbose_name_plural': 'Ethnic Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Genders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('cover_letter', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=300)),
                ('portfolio_url', models.URLField(blank=True, max_length=300)),
                ('languages', models.CharField(blank=True, max_length=500)),
                ('availability', models.CharField(blank=True, choices=[('Immediately', 'Immediately'), ('1 Month Notice', '1 Month Notice'), ('2 Months Notice', '2 Months Notice'), ('3 Months Notice', '3 Months Notice'), ('Not Available', 'Not Available')], max_length=50)),
                ('expected_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_detail', to='accounts.jobseekeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceo_override', models.BooleanField(default=False)),
                ('ceo_override_reason', models.TextField(blank=True, null=True)),
                ('ceo_selected', models.BooleanField(default=False)),
                ('cv', models.FileField(upload_to='media/cvs/')),
                ('cover_letter', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interviewed'), ('selected_top_five', 'Selected Top Five'), ('board_review', 'Board Review'), ('selected_top_three', 'Selected Top Three'), ('ceo_review', 'CEO Review'), ('ceo_approved', 'CEO Approved'), ('hr_appoints', 'HR Appoints'), ('appointed', 'Appointed'), ('not_selected', 'Not Selected')], default='submitted', max_length=50)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('interview_locked', models.BooleanField(default=False)),
                ('profile_snapshot', models.JSONField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.jobseekeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='recruitment.county')),
            ],
            options={
                'verbose_name': 'Constituency',
                'verbose_name_plural': 'Constituencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('year_completed', models.IntegerField()),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('cert_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_qualifications', to='accounts.jobseekeraccount')),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruitment.educationlevel')),
            ],
            options={
                'verbose_name': 'Academic Qualification',
                'verbose_name_plural': 'Academic Qualifications',
                'ordering': ['education_level__rank'],
            },
        ),
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('second_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_no', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('disability_status', models.CharField(blank=True, max_length=50, null=True)),
                ('disability_other', models.CharField(blank=True, max_length=255, null=True)),
                ('disability_no', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.constituency')),
                ('ethnic_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.ethnicgroup')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.gender')),
                ('home_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.county')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.jobseekeraccount')),
            ],
            options={
                'verbose_name': 'Job Seeker Profile',
                'verbose_name_plural': 'Job Seeker Profiles',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('unique_ref', models.CharField(editable=False, max_length=100, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.jobseekeraccount')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruitment.documenttype')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='recruitment.jobseekerprofile')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalBodyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_name', models.CharField(max_length=255)),
                ('membership_no', models.CharField(max_length=100)),
                ('year_joined', models.PositiveIntegerField()),
                ('expiry_year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_memberships', to='accounts.jobseekeraccount')),
            ],
            options={
                'ordering': ['-year_joined'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=255)),
                ('awarding_body', models.CharField(max_length=255)),
                ('year_obtained', models.PositiveIntegerField()),
                ('expiry_year', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('cert_number', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_qualifications', to='accounts.jobseekeraccount')),
            ],
            options={
                'ordering': ['-year_obtained'],
            },
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_counties', to='recruitment.county')),
            ],
            options={
                'verbose_name': 'Sub County',
                'verbose_name_plural': 'Sub Counties',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.subcounty'),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_category', models.CharField(choices=[('10-5', 'Grade 10-5'), ('4-1', 'Grade 4-1')], default='4-1', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('advert_pdf', models.FileField(upload_to='media/vacancy_adverts/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('longlisting', 'Longlisting'), ('shortlisting', 'Shortlisting'), ('interviews', 'Interviews'), ('top_three_selected', 'Top Three Selected'), ('pending_ceo_approval', 'Pending CEO Approval'), ('approved', 'Approved'), ('appointed', 'Appointed')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ranking_finalized', models.BooleanField(default=False)),
                ('vacancy_type', models.CharField(choices=[('external', 'External'), ('internal', 'Internal')], default='external', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TieBreakDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('selected_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.application')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='CEODecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_override', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('selected_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.application')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointed_at', models.DateTimeField(auto_now_add=True)),
                ('appointment_letter', models.FileField(blank=True, null=True, upload_to='media/appointments/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.application')),
                ('appointed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.vacancy')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.vacancy'),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='recruitment.constituency')),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Wards',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.ward'),
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('employment_type', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Volunteer', 'Volunteer'), ('Attachment', 'Attachment')], max_length=50)),
                ('start_month', models.PositiveIntegerField()),
                ('start_year', models.PositiveIntegerField()),
                ('end_month', models.PositiveIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('duties', models.TextField(blank=True)),
                ('exit_reason', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='accounts.jobseekeraccount')),
            ],
            options={
                'ordering': ['-start_year', '-start_month'],
            },
        ),
        migrations.CreateModel(
            name='InterviewScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remarks', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='recruitment.application')),
                ('panelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('application', 'panelist')},
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee_no', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('period_known', models.CharField(choices=[('Less than 1 year', 'Less than 1 year'), ('1 - 2 years', '1 - 2 years'), ('3 - 5 years', '3 - 5 years'), ('6 - 10 years', '6 - 10 years'), ('Over 10 years', 'Over 10 years')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referees', to='accounts.jobseekeraccount')),
            ],
            options={
                'ordering': ['referee_no'],
                'unique_together': {('user', 'referee_no')},
            },
        ),
        migrations.CreateModel(
            name='PanelAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('panelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_assignments', to='recruitment.vacancy')),
            ],
            options={
                'unique_together': {('vacancy', 'panelist')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('vacancy', 'applicant')},
        ),
    ]
