# Generated by Django 6.0.2 on 2026-03-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_locked',
            field=models.BooleanField(default=False),
        ),
    ]
