# Generated by Django 6.0.2 on 2026-02-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_populate_genders'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthnicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Ethnic Group',
                'verbose_name_plural': 'Ethnic Groups',
                'ordering': ['name'],
            },
        ),
    ]
