# Generated by Django 6.0.2 on 2026-03-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_application_interview_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ceo_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='ceo_override_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ceo_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interviewed'), ('selected_top_three', 'Top Three'), ('approved', 'Approved'), ('selected', 'Selected'), ('not_selected', 'Not Selected'), ('ceo_review', 'CEO Review'), ('ceo_approved', 'CEO Approved'), ('appointed', 'Appointed')], default='submitted', max_length=50),
        ),
    ]
