# Generated by Django 6.0.2 on 2026-02-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_application_vacancy_tiebreakdecision_ceodecision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
