# Generated by Django 6.0.2 on 2026-02-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_jobseekerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='salutation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='second_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
