# Generated by Django 6.0.2 on 2026-02-28 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_academicqualification'),
        ('recruitment', '0011_jobseekerprofile_salutation_jobseekerprofile_surname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rank', models.IntegerField(unique=True)),
                ('is_higher_education', models.BooleanField(default=False)),
                ('is_foreign', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Education Level',
                'verbose_name_plural': 'Education Levels',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('unique_ref', models.CharField(editable=False, max_length=100, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='recruitment.jobseekerprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.jobseekeraccount')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruitment.documenttype')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('year_completed', models.IntegerField()),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('cert_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_qualifications', to='accounts.jobseekeraccount')),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruitment.educationlevel')),
            ],
            options={
                'verbose_name': 'Academic Qualification',
                'verbose_name_plural': 'Academic Qualifications',
                'ordering': ['education_level__rank'],
            },
        ),
    ]
