# Generated by Django 6.0.2 on 2026-02-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_remove_vacancy_valid_until_vacancy_end_date_and_more'),
        ('recruitment', '0011_jobseekerprofile_salutation_jobseekerprofile_surname_and_more'),
    ]

    operations = [
    ]
