# Generated by Django 6.0.2 on 2026-02-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_merge_20260228_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_type',
            field=models.CharField(choices=[('external', 'External'), ('internal', 'Internal')], default='external', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(upload_to='media/cvs/'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_letter',
            field=models.FileField(blank=True, null=True, upload_to='media/appointments/'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='advert_pdf',
            field=models.FileField(upload_to='media/vacancy_adverts/'),
        ),
    ]
