# Generated by Django 6.0.2 on 2026-02-28 09:33

from django.db import migrations

def populate_education_levels(apps, schema_editor):
    EducationLevel = apps.get_model('recruitment', 'EducationLevel')

    levels = [
        # rank, name, is_higher_education, is_foreign
        (1,  'PhD / Doctorate',                    True,  False),
        (2,  'Masters Degree',                     True,  False),
        (3,  'Bachelor\'s Degree',                 True,  False),
        (4,  'Higher National Diploma (HND)',       True,  False),
        (5,  'Diploma',                             True,  False),
        (6,  'Certificate',                         True,  False),
        (7,  'Kenya Certificate of Secondary Education (KCSE)', False, False),
        (8,  'Kenya Certificate of Primary Education (KCPE)',   False, False),
        # Foreign equivalents
        (9,  'International Baccalaureate (IB)',    False, True),
        (10, 'A-Levels (British System)',           False, True),
        (11, 'O-Levels (British System)',           False, True),
        (12, 'GED (American System)',               False, True),
        (13, 'IGCSE',                               False, True),
        (14, 'Other Foreign Qualification',         False, True),
    ]

    for rank, name, is_higher, is_foreign in levels:
        EducationLevel.objects.get_or_create(
            rank=rank,
            defaults={
                'name':                name,
                'is_higher_education': is_higher,
                'is_foreign':          is_foreign,
            }
        )


def reverse_education_levels(apps, schema_editor):
    EducationLevel = apps.get_model('recruitment', 'EducationLevel')
    EducationLevel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_populate_constituencies'),
    ]

    operations = [
        migrations.RunPython(populate_education_levels, reverse_education_levels),
    ]
