# Generated by Django 6.0.2 on 2026-02-28 09:33

from django.db import migrations

def populate_document_types(apps, schema_editor):
    DocumentType = apps.get_model('recruitment', 'DocumentType')

    types = [
        ('National ID',                  'Kenya National Identity Card'),
        ('Passport',                     'Valid Travel Passport'),
        ('KCPE Certificate',             'Kenya Certificate of Primary Education'),
        ('KCSE Certificate',             'Kenya Certificate of Secondary Education'),
        ('Diploma Certificate',          'Diploma level certificate'),
        ('Degree Certificate',           'Undergraduate degree certificate'),
        ('Masters Certificate',          'Masters degree certificate'),
        ('PhD Certificate',              'Doctorate certificate'),
        ('Academic Transcript',          'Official academic transcripts'),
        ('Professional Certificate',     'Professional qualification certificate'),
        ('CV / Resume',                  'Curriculum Vitae or Resume'),
        ('Cover Letter',                 'Application cover letter'),
        ('Good Conduct Certificate',     'Certificate of Good Conduct from DCI'),
        ('HELB Clearance',               'Higher Education Loans Board clearance'),
        ('EACC Clearance',               'Ethics and Anti-Corruption Commission clearance'),
        ('KRA Tax Compliance',           'Kenya Revenue Authority tax compliance certificate'),
        ('NHIF Clearance',               'National Hospital Insurance Fund clearance'),
        ('NSSF Clearance',               'National Social Security Fund clearance'),
        ('CRB Clearance',                'Credit Reference Bureau clearance'),
        ('Other',                        'Any other supporting document'),
    ]

    for name, description in types:
        DocumentType.objects.get_or_create(name=name, defaults={'description': description})


def reverse_document_types(apps, schema_editor):
    DocumentType = apps.get_model('recruitment', 'DocumentType')
    DocumentType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0013_populate_education_levels'),
    ]

    operations = [
        migrations.RunPython(populate_document_types, reverse_document_types),
    ]
