# Generated by Django 6.0.2 on 2026-02-28 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0013_vacancy_vacancy_type_alter_application_cv_and_more'),
        ('recruitment', '0014_populate_document_types'),
    ]

    operations = [
    ]
