# Generated by Django 6.0.2 on 2026-02-27 13:55

from django.db import migrations
def populate_ethnic_groups(apps, schema_editor):
    EthnicGroup = apps.get_model('recruitment', 'EthnicGroup')

    groups = [
        # Bantu Groups
        'Kikuyu',
        'Luhya',
        'Kamba',
        'Kisii/Gusii',
        'Meru',
        'Mijikenda',
        'Taita',
        'Embu',
        'Tharaka',
        'Basuba/Suba',
        'Kuria',
        'Mbere',
        'Taveta',
        'Luo',
        'Kalenjin',
        'Turkana',
        'Maasai',
        'Samburu',
        'Teso/Iteso',
        'Njemps/Ilchamus',
        'Ogiek',
        'Somali',
        'Borana',
        'Rendille',
        'Gabra',
        'Sakuye',
        'Burji',
        'Orma',
        'Gosha',
        'Daasanach/Merille',
        'Arab',
        'Asian (Kenyan)',
        'European (Kenyan)',
        'Swahili',
        'Other',
        'Prefer not to say',
        'Aweer/Waat',
        'Bajun',
        'Dahalo',
        'Dasnach-Shagli',
        'Dorobo',
        'Elmolo',
        'American (Kenyan)',
        'Konso',
        'Makonde',
        'Masai',
        'Nubi',
        'Pokomo',
        'Walwana/Malakote',
        'Wayyu'
]

    for group in groups:
        EthnicGroup.objects.get_or_create(name=group)


def reverse_ethnic_groups(apps, schema_editor):
    EthnicGroup = apps.get_model('recruitment', 'EthnicGroup')
    EthnicGroup.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0014_populate_document_types'),
    ]

    operations = [
        migrations.RunPython(populate_ethnic_groups, reverse_ethnic_groups),
    ]
