# Generated by Django 6.0.2 on 2026-02-28 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_professionalqualification_user_and_more'),
        ('recruitment', '0016_alter_application_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('employment_type', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Volunteer', 'Volunteer'), ('Attachment', 'Attachment')], max_length=50)),
                ('start_month', models.PositiveIntegerField()),
                ('start_year', models.PositiveIntegerField()),
                ('end_month', models.PositiveIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('duties', models.TextField(blank=True)),
                ('exit_reason', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='accounts.jobseekeraccount')),
            ],
            options={
                'ordering': ['-start_year', '-start_month'],
            },
        ),
    ]
