# Generated by Django 6.0.2 on 2026-03-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0017_populate_subcounties'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='disability_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
