# Generated by Django 6.0.2 on 2026-02-28 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_professionalqualification_user_and_more'),
        ('recruitment', '0017_workhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('cover_letter', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=300)),
                ('portfolio_url', models.URLField(blank=True, max_length=300)),
                ('languages', models.CharField(blank=True, max_length=500)),
                ('availability', models.CharField(blank=True, choices=[('Immediately', 'Immediately'), ('1 Month Notice', '1 Month Notice'), ('2 Months Notice', '2 Months Notice'), ('3 Months Notice', '3 Months Notice'), ('Not Available', 'Not Available')], max_length=50)),
                ('expected_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_detail', to='accounts.jobseekeraccount')),
            ],
        ),
    ]
