# Generated by Django 6.0.2 on 2026-03-03 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0017_populate_subcounties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('longlisting', 'Longlisting'), ('committee_stage', 'Committee Appointed'), ('shortlisting', 'Shortlisting'), ('interviews', 'Interviews'), ('top_three_selected', 'Top Three Selected'), ('pending_ceo_approval', 'Pending CEO Approval'), ('approved', 'Approved'), ('appointed', 'Appointed')], default='draft', max_length=50),
        ),
        migrations.CreateModel(
            name='ShortlistVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlist_votes', to='recruitment.application')),
                ('committee_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlist_votes', to='recruitment.vacancy')),
            ],
            options={
                'unique_together': {('vacancy', 'committee_member', 'application')},
            },
        ),
    ]
