# Generated by Django 6.0.2 on 2026-03-03 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_jobseekeraccount_is_employee'),
        ('recruitment', '0018_jobseekerprofile_disability_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalBodyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_name', models.CharField(max_length=255)),
                ('membership_no', models.CharField(max_length=100)),
                ('year_joined', models.PositiveIntegerField()),
                ('expiry_year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_memberships', to='accounts.jobseekeraccount')),
            ],
            options={
                'ordering': ['-year_joined'],
            },
        ),
    ]
