# Generated by Django 6.0.2 on 2026-03-03 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0018_alter_vacancy_status_shortlistvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='panelassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='panelassignment',
            name='committee_type',
            field=models.CharField(blank=True, choices=[('shortlisting', 'Shortlisting'), ('interview', 'Interview')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='panelassignment',
            name='status',
            field=models.CharField(choices=[('shortlisting', 'Shortlisting'), ('interview', 'Interview')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='panelassignment',
            unique_together={('vacancy', 'panelist', 'committee_type')},
        ),
    ]
