# Generated by Django 6.0.2 on 2026-02-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0018_additionaldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='disability_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='employee_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
