# Generated by Django 6.0.2 on 2026-03-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0019_professionalbodymembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='grade_category',
            field=models.CharField(choices=[('10-5', 'Grade 10-5'), ('4-1', 'Grade 4-1')], default='4-1', max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interviewed'), ('selected_top_five', 'Selected Top Five'), ('board_review', 'Board Review'), ('selected_top_three', 'Selected Top Three'), ('ceo_review', 'CEO Review'), ('ceo_approved', 'CEO Approved'), ('hr_appoints', 'HR Appoints'), ('appointed', 'Appointed'), ('not_selected', 'Not Selected')], default='submitted', max_length=50),
        ),
    ]
