# Generated by Django 6.0.2 on 2026-03-03 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_jobseekeraccount_is_employee'),
        ('recruitment', '0019_professionalbodymembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee_no', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('period_known', models.CharField(choices=[('Less than 1 year', 'Less than 1 year'), ('1 - 2 years', '1 - 2 years'), ('3 - 5 years', '3 - 5 years'), ('6 - 10 years', '6 - 10 years'), ('Over 10 years', 'Over 10 years')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referees', to='accounts.jobseekeraccount')),
            ],
            options={
                'ordering': ['referee_no'],
                'unique_together': {('user', 'referee_no')},
            },
        ),
    ]
