# Generated by Django 6.0.2 on 2026-03-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0021_seed_jobapplication_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldetail',
            name='availability',
            field=models.CharField(blank=True, choices=[('Immediately', 'Immediately'), ('1 Week Notice', '1 Week Notice'), ('2 Weeks Notice', '2 Weeks Notice'), ('3 Weeks Notice', '3 Weeks Notice'), ('1 Month Notice', '1 Month Notice'), ('2 Months Notice', '2 Months Notice'), ('3 Months Notice', '3 Months Notice'), ('Not Available', 'Not Available')], max_length=50),
        ),
        migrations.AlterField(
            model_name='additionaldetail',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='cover_letters/'),
        ),
    ]
