# Generated by Django 6.0.2 on 2026-03-04 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_jobseekeraccount_is_employee'),
        ('recruitment', '0022_alter_additionaldetail_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='application_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruitment.jobapplicationstatus'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jobseekeraccount'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.vacancy'),
        ),
        migrations.CreateModel(
            name='VacancyApplicationCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('vacancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_counter', to='recruitment.vacancy')),
            ],
        ),
    ]
