# Generated by Django 6.0.3 on 2026-03-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0025_shortlistingdecision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('longlisting', 'Longlisting'), ('committee_stage', 'Committee Appointed'), ('shortlisting', 'Shortlisting Stage'), ('interviews', 'Interviews'), ('top_three_selected', 'Top Three Selected'), ('pending_ceo_approval', 'Pending CEO Approval'), ('approved', 'Approved'), ('appointed', 'Appointed')], default='draft', max_length=50),
        ),
    ]
