# Generated by Django 6.0.3 on 2026-03-05 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0027_remove_shortlistingcommittee_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortlistingcommittee',
            name='member',
        ),
        migrations.AddField(
            model_name='shortlistingcommittee',
            name='members',
            field=models.ManyToManyField(related_name='shortlisting_committees', to=settings.AUTH_USER_MODEL),
        ),
    ]
