# Generated by Django 6.0.2 on 2026-03-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0028_remove_shortlistingcommittee_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='advert_pdf',
            field=models.FileField(blank=True, null=True, upload_to='vacancy_adverts/'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='grade_category',
            field=models.CharField(choices=[('10-5', 'Grade 10-5'), ('4-1', 'Grade 4-1')], default='4-1', max_length=20),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('longlisting', 'Longlisting'), ('committee_stage', 'Committee Appointed'), ('shortlisting', 'Shortlisting Stage'), ('interviews', 'Interviews'), ('top_three_selected', 'Top Three Selected'), ('pending_ceo_approval', 'Pending CEO Approval'), ('approved', 'Approved'), ('appointed', 'Appointed')], default='draft', max_length=50),
        ),
    ]
