# Generated by Django 6.0.3 on 2026-03-05 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0029_remove_interviewscore_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSectionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interview_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.interviewscore')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.interviewsection')),
            ],
        ),
    ]
