# Generated by Django 6.0.3 on 2026-03-05 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0030_interviewsectionscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsectionscore',
            name='interview_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_scores', to='recruitment.interviewscore'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewsectionscore',
            unique_together={('interview_score', 'section')},
        ),
    ]
