# Generated by Django 6.0.2 on 2026-03-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0033_longlisting_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationlevel',
            name='level',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='longlist_decision',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='longlist_decision_at',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='longlist_decision_by',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='longlist_notes',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='screening_flags',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='screening_passed',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='screening_ran_at',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='screening_reasons',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='screening_criteria',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='LonglistReviewLog',
        ),
    ]
