# Generated by Django 6.0.2 on 2026-03-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0033_longlisting_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='screening_flags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='screening_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='screening_reasons',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='longlistreviewlog',
            name='action',
            field=models.CharField(choices=[('viewed', 'Viewed Application'), ('shortlisted', 'Marked Shortlist'), ('rejected', 'Marked Reject'), ('held', 'Marked Hold'), ('override', 'Override System Decision'), ('assigned', 'Assigned to Officer'), ('bulk_shortlist', 'Bulk Shortlist'), ('bulk_reject', 'Bulk Reject'), ('bulk_assign', 'Bulk Assign'), ('note_added', 'Added Note'), ('decision_changed', 'Decision Changed'), ('system_screening', 'System Auto-Screening')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='screening_criteria',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
