# Generated by Django 6.0.2 on 2026-03-05 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0034_remove_educationlevel_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='longlist_decision',
            field=models.CharField(blank=True, choices=[('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hold', 'Hold')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='longlist_decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='longlist_decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='longlist_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='longlist_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='screening_flags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='screening_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='screening_ran_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='screening_reasons',
            field=models.JSONField(default=list),
        ),
    ]
