# Generated by Django 6.0.3 on 2026-03-05 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0035_jobapplication_assigned_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='panelassignment',
            name='signed_decline_document',
            field=models.FileField(blank=True, null=True, upload_to='panel_declines/'),
        ),
        migrations.AlterField(
            model_name='panelassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PanelistReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidates_interviewed', models.IntegerField(default=0)),
                ('summary', models.TextField()),
                ('recommendations', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('panelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.vacancy')),
            ],
            options={
                'unique_together': {('vacancy', 'panelist')},
            },
        ),
    ]
