# Generated by Django 6.0.3 on 2026-03-05 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0036_panelassignment_signed_decline_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panelistreport',
            old_name='summary',
            new_name='report_summary',
        ),
        migrations.AddField(
            model_name='panelistreport',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.panelassignment'),
        ),
        migrations.AlterField(
            model_name='panelistreport',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_reports', to='recruitment.vacancy'),
        ),
    ]
