# Generated by Django 6.0.3 on 2026-03-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0044_recreate_committee_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortlistlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='committee_appointed_at',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='is_overdue',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='shortlist_finalised_at',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='shortlist_finalised_by',
        ),
        migrations.AlterField(
            model_name='additionaldetail',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='media/cover_letters/'),
        ),
        migrations.AlterField(
            model_name='additionaldetail',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='media/cvs/'),
        ),
        migrations.AlterField(
            model_name='committeescore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='committeescoreamendment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='media/documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='panelassignment',
            name='signed_decline_document',
            field=models.FileField(blank=True, null=True, upload_to='media/panel_declines/'),
        ),
        migrations.AlterField(
            model_name='shortlistconsent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shortlistingcommittee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shortlistlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shortlistpick',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='advert_pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/vacancy_adverts/'),
        ),
    ]
