# Generated by Django 6.0.3 on 2026-03-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0045_alter_shortlistlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldetail',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='cover_letters/'),
        ),
        migrations.AlterField(
            model_name='additionaldetail',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(upload_to='cvs/'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_letter',
            field=models.FileField(blank=True, null=True, upload_to='appointments/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='panelassignment',
            name='signed_decline_document',
            field=models.FileField(blank=True, null=True, upload_to='panel_declines/'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='advert_pdf',
            field=models.FileField(blank=True, null=True, upload_to='<div class="ufaa-table-wrapper">vacancy_adverts/'),
        ),
    ]
