# Generated by Django 6.0.2 on 2026-03-09 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0046_alter_additionaldetail_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='academic_qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='recruitment.academicqualification'),
        ),
        migrations.AddField(
            model_name='document',
            name='professional_qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='recruitment.professionalqualification'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='advert_pdf',
            field=models.FileField(blank=True, null=True, upload_to='vacancy_adverts/'),
        ),
    ]
