# Generated by Django 6.0.2 on 2026-03-09 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0047_document_academic_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='recruitment.professionalbodymembership'),
        ),
    ]
