# Generated by Django 6.0.2 on 2026-03-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0048_document_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='membership',
        ),
    ]
