# Generated by Django 6.0.2 on 2026-03-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0050_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeevote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shortlistingcommittee',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shortlistlog',
            name='action',
            field=models.CharField(choices=[('member_appointed', 'Member Appointed'), ('member_removed', 'Member Removed'), ('member_acknowledged', 'Member Acknowledged Appointment'), ('vote_saved', 'Vote Saved as Draft'), ('vote_submitted', 'Vote Submitted'), ('all_votes_in', 'All Votes Submitted — Shortlist Generated'), ('applicant_notified', 'Applicant Notified of Outcome'), ('emails_sent', 'Bulk Emails Sent'), ('override_requested', 'Override Requested'), ('override_approved', 'Override Approved')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shortlistresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
