# Generated by Django 6.0.2 on 2026-03-12 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0052_coi_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── Clear unique_together BEFORE removing fields ──────────────────────
        migrations.AlterUniqueTogether(
            name='interviewsectionscore',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='interviewsectionscore',
            name='section',
        ),
        migrations.RemoveField(
            model_name='interviewsectionscore',
            name='interview_score',
        ),
        migrations.RemoveField(
            model_name='interviewtemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='interview_template',
        ),
        migrations.AlterUniqueTogether(
            name='panelassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='panelassignment',
            name='panelist',
        ),
        migrations.RemoveField(
            model_name='panelassignment',
            name='vacancy',
        ),
        migrations.RemoveField(
            model_name='panelistreport',
            name='assignment',
        ),
        migrations.AlterUniqueTogether(
            name='panelistreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='panelistreport',
            name='panelist',
        ),
        migrations.RemoveField(
            model_name='panelistreport',
            name='vacancy',
        ),
        migrations.AlterUniqueTogether(
            name='shortlistingdecision',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shortlistingdecision',
            name='application',
        ),
        migrations.RemoveField(
            model_name='shortlistingdecision',
            name='committee_member',
        ),
        migrations.AlterUniqueTogether(
            name='shortlistvote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shortlistvote',
            name='application',
        ),
        migrations.RemoveField(
            model_name='shortlistvote',
            name='committee_member',
        ),
        migrations.RemoveField(
            model_name='shortlistvote',
            name='vacancy',
        ),
        migrations.AlterModelOptions(
            name='interviewscore',
            options={'ordering': ['criterion__order', 'criterion__id']},
        ),
        migrations.AddField(
            model_name='interviewscore',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewscore',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interviewscore',
            name='panel_member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interview_scores_given', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewscore',
            name='score',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Must be between 0 and criterion.max_score.', max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewscore',
            name='scored_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='interviewscore',
            name='vacancy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interview_scores', to='recruitment.vacancy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewscore',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_scores', to='recruitment.jobapplication'),
        ),
        migrations.AlterField(
            model_name='interviewscore',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shortlistingcommittee',
            name='coi_declared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shortlistingcommittee',
            name='conflict_declared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shortlistingcommittee',
            name='conflict_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shortlistingcommittee',
            name='has_conflict',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InterviewCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('max_score', models.PositiveSmallIntegerField(help_text='Maximum marks available for this criterion.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_criteria', to='recruitment.vacancy')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('vacancy', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='interviewscore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='interviewscore',
            name='criterion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='recruitment.interviewcriterion'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='interviewscore',
            unique_together={('vacancy', 'application', 'panel_member', 'criterion')},
        ),
        migrations.CreateModel(
            name='InterviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('panel_appointed', 'Panel Member Appointed'), ('panel_removed', 'Panel Member Removed'), ('panel_notified', 'Panel Member Notified'), ('member_acknowledged', 'Panel Member Acknowledged'), ('coi_declared', 'COI Declared'), ('schedule_created', 'Interview Schedule Created'), ('schedule_updated', 'Interview Schedule Updated'), ('slot_assigned', 'Interview Slot Assigned'), ('candidate_notified', 'Candidate Notified'), ('score_saved', 'Score Saved as Draft'), ('score_submitted', 'Score Submitted'), ('all_scores_in', 'All Scores In — Results Computed')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('performed_by_label', models.CharField(blank=True, max_length=200)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_logs', to='recruitment.jobapplication')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_actions', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_logs', to='recruitment.vacancy')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InterviewPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('coi_declared', models.BooleanField(default=False)),
                ('has_conflict', models.BooleanField(default=False)),
                ('conflict_reason', models.TextField(blank=True)),
                ('conflict_declared_at', models.DateTimeField(blank=True, null=True)),
                ('scores_submitted', models.BooleanField(default=False)),
                ('scores_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notified', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('appointed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_appointments_made', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_assignments', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_panel', to='recruitment.vacancy')),
            ],
            options={
                'unique_together': {('vacancy', 'member')},
            },
        ),
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_possible', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_result', to='recruitment.jobapplication')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_results', to='recruitment.vacancy')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('vacancy', 'application')},
            },
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_type', models.CharField(choices=[('physical', 'Physical (In-Person)'), ('online', 'Online')], default='physical', max_length=20)),
                ('venue', models.TextField(help_text='Physical address OR online meeting link.')),
                ('instructions', models.TextField(blank=True, help_text='Any preparatory instructions sent to candidates.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidates_notified', models.BooleanField(default=False)),
                ('candidates_notified_at', models.DateTimeField(blank=True, null=True)),
                ('panel_notified', models.BooleanField(default=False)),
                ('panel_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_schedules_created', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_schedule', to='recruitment.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('venue_override', models.TextField(blank=True, help_text='Leave blank to use the schedule venue/link.')),
                ('notified', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_slot', to='recruitment.jobapplication')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='recruitment.interviewschedule')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_slots', to='recruitment.vacancy')),
            ],
            options={
                'ordering': ['interview_date', 'interview_time'],
            },
        ),
        migrations.DeleteModel(
            name='InterviewSection',
        ),
        migrations.DeleteModel(
            name='InterviewSectionScore',
        ),
        migrations.DeleteModel(
            name='PanelAssignment',
        ),
        migrations.DeleteModel(
            name='PanelistReport',
        ),
        migrations.DeleteModel(
            name='ShortlistingDecision',
        ),
        migrations.DeleteModel(
            name='ShortlistVote',
        ),
        migrations.RemoveField(
            model_name='interviewscore',
            name='panelist',
        ),
        migrations.RemoveField(
            model_name='interviewscore',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='interviewscore',
            name='template',
        ),
        migrations.RemoveField(
            model_name='interviewscore',
            name='total_score',
        ),
        migrations.DeleteModel(
            name='InterviewTemplate',
        ),
    ]