# Generated by Django 6.0.2 on 2026-03-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0056_seed_job_application_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longlistreviewlog',
            name='action',
            field=models.CharField(choices=[('viewed', 'Viewed Application'), ('shortlisted', 'Marked Shortlist'), ('rejected', 'Marked Reject'), ('held', 'Marked Hold'), ('override', 'Override System Decision'), ('assigned', 'Assigned to Officer'), ('bulk_shortlist', 'Bulk Shortlist'), ('bulk_reject', 'Bulk Reject'), ('bulk_assign', 'Bulk Assign'), ('note_added', 'Added Note'), ('decision_changed', 'Decision Changed'), ('system_screening', 'System Auto-Screening'), ('top_candidate_selected', 'Top Candidate Selected by HR'), ('submitted_to_ceo', 'Submitted to CEO for Review'), ('ceo_selection_made', 'CEO Selection Made'), ('appointment_issued', 'Appointment Issued by HR')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('longlisting', 'Longlisting'), ('committee_stage', 'Committee Stage'), ('shortlisting', 'Shortlisting Stage'), ('interview_scheduling', 'Interview Scheduling'), ('interviews', 'Interviews Complete'), ('ceo_review', 'CEO Review'), ('ceo_approved', 'CEO Approved'), ('appointed', 'Appointed')], default='draft', max_length=50),
        ),
    ]
