# Generated by Django 6.0.2 on 2026-03-19 08:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruitment', '0057_alter_longlistreviewlog_action_alter_vacancy_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_apps', models.IntegerField(default=0)),
                ('longlisted', models.IntegerField(default=0)),
                ('final_longlisted', models.IntegerField(default=0)),
                ('shortlisted', models.IntegerField(default=0)),
                ('interviewed', models.IntegerField(default=0)),
                ('top_candidate', models.IntegerField(default=0)),
                ('appointed', models.IntegerField(default=0)),
                ('not_selected', models.IntegerField(default=0)),
                ('longlist_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('shortlist_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('interview_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('appointment_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('days_open', models.IntegerField(blank=True, null=True)),
                ('days_longlisting', models.IntegerField(blank=True, null=True)),
                ('days_shortlisting', models.IntegerField(blank=True, null=True)),
                ('days_interviews', models.IntegerField(blank=True, null=True)),
                ('days_total', models.IntegerField(blank=True, null=True)),
                ('avg_interview_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_interview_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('min_interview_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('score_std_dev', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ceo_selected_rank', models.IntegerField(blank=True, null=True)),
                ('ceo_override', models.BooleanField(default=False)),
                ('committee_size', models.IntegerField(default=0)),
                ('committee_coi_count', models.IntegerField(default=0)),
                ('shortlist_override_count', models.IntegerField(default=0)),
                ('gender_breakdown', models.JSONField(default=dict)),
                ('county_breakdown', models.JSONField(default=dict)),
                ('edu_level_breakdown', models.JSONField(default=dict)),
                ('pwd_count', models.IntegerField(default=0)),
                ('vacancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshot', to='recruitment.vacancy')),
            ],
            options={
                'verbose_name': 'Vacancy Analytics Snapshot',
                'verbose_name_plural': 'Vacancy Analytics Snapshots',
                'ordering': ['-snapped_at'],
            },
        ),
    ]
