# Generated by Django 6.0.2 on 2026-03-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalqualification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workhistory',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AdditionalDetail',
        ),
        migrations.DeleteModel(
            name='ProfessionalQualification',
        ),
        migrations.DeleteModel(
            name='WorkHistory',
        ),
    ]
