# Generated by Django 6.0.2 on 2026-03-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekeraccount',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
    ]
