# Generated by Django 6.0.2 on 2026-02-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_jobseekeraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekeraccount',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
