# Generated by Django 6.0.2 on 2026-03-07 09:16

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_jobseekeraccount_is_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekeraccount',
            name='password_reset_expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobseekeraccount',
            name='password_reset_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='jobseekeraccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
