# Generated by Django 6.0.2 on 2026-03-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_jobseekeraccount_password_reset_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekeraccount',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobseekeraccount',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
