# Generated by Django 6.0.2 on 2026-02-26 14:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_jobseekeraccount_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekeraccount',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
