# Generated by Django 6.0.2 on 2026-02-26 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_academicqualification_additionaldetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicqualification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='academicqualification',
            name='institution',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='additionaldetail',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv_uploads/'),
        ),
        migrations.AddField(
            model_name='additionaldetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='professionalqualification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workhistory',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='academicqualification',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='academic_certificates/'),
        ),
        migrations.AlterField(
            model_name='academicqualification',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to='academic_transcripts/'),
        ),
        migrations.AlterField(
            model_name='additionaldetail',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionalqualification',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='professional_certificates/'),
        ),
    ]
