# Generated by Django 6.0.2 on 2026-02-27 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_jobseekeraccount_verification_token'),
        ('accounts', '0005_academicqualification_created_at_and_more'),
    ]

    operations = [
    ]
