# Generated by Django 6.0.2 on 2026-02-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20260227_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='salutation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='surname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='disability_status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='ethnic_group',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='gender',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='home_county',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='second_name',
            field=models.CharField(max_length=255),
        ),
    ]
