# Generated by Django 6.0.2 on 2026-02-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_jobseekerprofile_salutation_jobseekerprofile_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='home_constituency',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='home_sub_county',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='home_ward',
            field=models.IntegerField(null=True),
        ),
    ]
