# Generated by Django 6.0.2 on 2026-02-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_jobseekerprofile_home_constituency_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobseekerProfile',
        ),
    ]
