# Generated by Django 6.0.2 on 2026-02-28 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_jobseekerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicQualification',
        ),
    ]
