# Generated by Django 6.0.2 on 2026-02-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_academicqualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalqualification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdditionalDetail',
        ),
        migrations.DeleteModel(
            name='ProfessionalQualification',
        ),
        migrations.DeleteModel(
            name='WorkHistory',
        ),
    ]
