# Generated by Django 6.0.2 on 2026-02-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_professionalqualification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekeraccount',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
    ]
